// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/tenant/v1/tenant.proto

package tenantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantStatus represents the lifecycle status of a tenant
type TenantStatus int32

const (
	TenantStatus_TENANT_STATUS_UNSPECIFIED  TenantStatus = 0
	TenantStatus_TENANT_STATUS_PROVISIONING TenantStatus = 1
	TenantStatus_TENANT_STATUS_ACTIVE       TenantStatus = 2
	TenantStatus_TENANT_STATUS_SUSPENDED    TenantStatus = 3
	TenantStatus_TENANT_STATUS_ARCHIVED     TenantStatus = 4
	TenantStatus_TENANT_STATUS_DELETED      TenantStatus = 5
)

// Enum value maps for TenantStatus.
var (
	TenantStatus_name = map[int32]string{
		0: "TENANT_STATUS_UNSPECIFIED",
		1: "TENANT_STATUS_PROVISIONING",
		2: "TENANT_STATUS_ACTIVE",
		3: "TENANT_STATUS_SUSPENDED",
		4: "TENANT_STATUS_ARCHIVED",
		5: "TENANT_STATUS_DELETED",
	}
	TenantStatus_value = map[string]int32{
		"TENANT_STATUS_UNSPECIFIED":  0,
		"TENANT_STATUS_PROVISIONING": 1,
		"TENANT_STATUS_ACTIVE":       2,
		"TENANT_STATUS_SUSPENDED":    3,
		"TENANT_STATUS_ARCHIVED":     4,
		"TENANT_STATUS_DELETED":      5,
	}
)

func (x TenantStatus) Enum() *TenantStatus {
	p := new(TenantStatus)
	*p = x
	return p
}

func (x TenantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tenant_v1_tenant_proto_enumTypes[0].Descriptor()
}

func (TenantStatus) Type() protoreflect.EnumType {
	return &file_proto_tenant_v1_tenant_proto_enumTypes[0]
}

func (x TenantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantStatus.Descriptor instead.
func (TenantStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_tenant_v1_tenant_proto_rawDescGZIP(), []int{0}
}

// Tenant represents a tenant entity
type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	SchemaName    string                 `protobuf:"bytes,5,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	Status        TenantStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=identity.tenant.v1.TenantStatus" json:"status,omitempty"`
	Plan          string                 `protobuf:"bytes,7,opt,name=plan,proto3" json:"plan,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,8,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactName   string                 `protobuf:"bytes,9,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	BillingEmail  string                 `protobuf:"bytes,10,opt,name=billing_email,json=billingEmail,proto3" json:"billing_email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_proto_tenant_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tenant) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *Tenant) GetStatus() TenantStatus {
	if x != nil {
		return x.Status
	}
	return TenantStatus_TENANT_STATUS_UNSPECIFIED
}

func (x *Tenant) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *Tenant) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *Tenant) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Tenant) GetBillingEmail() string {
	if x != nil {
		return x.BillingEmail
	}
	return ""
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tenant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GetTenantRequest is the request for GetTenant
type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *GetTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// GetBySlugRequest is the request for GetTenantBySlug
type GetBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBySlugRequest) Reset() {
	*x = GetBySlugRequest{}
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBySlugRequest) ProtoMessage() {}

func (x *GetBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetBySlugRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_v1_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *GetBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// ValidateTenantRequest is the request for ValidateTenant
type ValidateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTenantRequest) Reset() {
	*x = ValidateTenantRequest{}
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTenantRequest) ProtoMessage() {}

func (x *ValidateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTenantRequest.ProtoReflect.Descriptor instead.
func (*ValidateTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_v1_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// ValidationResponse contains tenant validation result
type ValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SchemaName    string                 `protobuf:"bytes,3,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	Status        TenantStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=identity.tenant.v1.TenantStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResponse) Reset() {
	*x = ValidationResponse{}
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResponse) ProtoMessage() {}

func (x *ValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResponse.ProtoReflect.Descriptor instead.
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_v1_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *ValidationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ValidationResponse) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *ValidationResponse) GetStatus() TenantStatus {
	if x != nil {
		return x.Status
	}
	return TenantStatus_TENANT_STATUS_UNSPECIFIED
}

func (x *ValidationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TenantResponse contains a single tenant
type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_v1_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *TenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// ListTenantsRequest is the request for ListTenants
type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Plan          string                 `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	Search        string                 `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_v1_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *ListTenantsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTenantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTenantsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTenantsRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *ListTenantsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// ListTenantsResponse contains a list of tenants with pagination
type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_v1_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_v1_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *ListTenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *ListTenantsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListTenantsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTenantsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTenantsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_proto_tenant_v1_tenant_proto protoreflect.FileDescriptor

const file_proto_tenant_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/tenant/v1/tenant.proto\x12\x12identity.tenant.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x03\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x1f\n" +
	"\vschema_name\x18\x05 \x01(\tR\n" +
	"schemaName\x128\n" +
	"\x06status\x18\x06 \x01(\x0e2 .identity.tenant.v1.TenantStatusR\x06status\x12\x12\n" +
	"\x04plan\x18\a \x01(\tR\x04plan\x12#\n" +
	"\rcontact_email\x18\b \x01(\tR\fcontactEmail\x12!\n" +
	"\fcontact_name\x18\t \x01(\tR\vcontactName\x12#\n" +
	"\rbilling_email\x18\n" +
	" \x01(\tR\fbillingEmail\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"/\n" +
	"\x10GetTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"&\n" +
	"\x10GetBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"4\n" +
	"\x15ValidateTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xbc\x01\n" +
	"\x12ValidationResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vschema_name\x18\x03 \x01(\tR\n" +
	"schemaName\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .identity.tenant.v1.TenantStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"D\n" +
	"\x0eTenantResponse\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.identity.tenant.v1.TenantR\x06tenant\"\x89\x01\n" +
	"\x12ListTenantsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04plan\x18\x04 \x01(\tR\x04plan\x12\x16\n" +
	"\x06search\x18\x05 \x01(\tR\x06search\"\xbe\x01\n" +
	"\x13ListTenantsResponse\x124\n" +
	"\atenants\x18\x01 \x03(\v2\x1a.identity.tenant.v1.TenantR\atenants\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages*\xbb\x01\n" +
	"\fTenantStatus\x12\x1d\n" +
	"\x19TENANT_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTENANT_STATUS_PROVISIONING\x10\x01\x12\x18\n" +
	"\x14TENANT_STATUS_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17TENANT_STATUS_SUSPENDED\x10\x03\x12\x1a\n" +
	"\x16TENANT_STATUS_ARCHIVED\x10\x04\x12\x19\n" +
	"\x15TENANT_STATUS_DELETED\x10\x052\x88\x03\n" +
	"\rTenantService\x12U\n" +
	"\tGetTenant\x12$.identity.tenant.v1.GetTenantRequest\x1a\".identity.tenant.v1.TenantResponse\x12[\n" +
	"\x0fGetTenantBySlug\x12$.identity.tenant.v1.GetBySlugRequest\x1a\".identity.tenant.v1.TenantResponse\x12c\n" +
	"\x0eValidateTenant\x12).identity.tenant.v1.ValidateTenantRequest\x1a&.identity.tenant.v1.ValidationResponse\x12^\n" +
	"\vListTenants\x12&.identity.tenant.v1.ListTenantsRequest\x1a'.identity.tenant.v1.ListTenantsResponseB:Z8github.com/cotai/tenant-manager/proto/tenant/v1;tenantv1b\x06proto3"

var (
	file_proto_tenant_v1_tenant_proto_rawDescOnce sync.Once
	file_proto_tenant_v1_tenant_proto_rawDescData []byte
)

func file_proto_tenant_v1_tenant_proto_rawDescGZIP() []byte {
	file_proto_tenant_v1_tenant_proto_rawDescOnce.Do(func() {
		file_proto_tenant_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tenant_v1_tenant_proto_rawDesc), len(file_proto_tenant_v1_tenant_proto_rawDesc)))
	})
	return file_proto_tenant_v1_tenant_proto_rawDescData
}

var file_proto_tenant_v1_tenant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_tenant_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_tenant_v1_tenant_proto_goTypes = []any{
	(TenantStatus)(0),             // 0: identity.tenant.v1.TenantStatus
	(*Tenant)(nil),                // 1: identity.tenant.v1.Tenant
	(*GetTenantRequest)(nil),      // 2: identity.tenant.v1.GetTenantRequest
	(*GetBySlugRequest)(nil),      // 3: identity.tenant.v1.GetBySlugRequest
	(*ValidateTenantRequest)(nil), // 4: identity.tenant.v1.ValidateTenantRequest
	(*ValidationResponse)(nil),    // 5: identity.tenant.v1.ValidationResponse
	(*TenantResponse)(nil),        // 6: identity.tenant.v1.TenantResponse
	(*ListTenantsRequest)(nil),    // 7: identity.tenant.v1.ListTenantsRequest
	(*ListTenantsResponse)(nil),   // 8: identity.tenant.v1.ListTenantsResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_tenant_v1_tenant_proto_depIdxs = []int32{
	0,  // 0: identity.tenant.v1.Tenant.status:type_name -> identity.tenant.v1.TenantStatus
	9,  // 1: identity.tenant.v1.Tenant.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: identity.tenant.v1.Tenant.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: identity.tenant.v1.ValidationResponse.status:type_name -> identity.tenant.v1.TenantStatus
	1,  // 4: identity.tenant.v1.TenantResponse.tenant:type_name -> identity.tenant.v1.Tenant
	1,  // 5: identity.tenant.v1.ListTenantsResponse.tenants:type_name -> identity.tenant.v1.Tenant
	2,  // 6: identity.tenant.v1.TenantService.GetTenant:input_type -> identity.tenant.v1.GetTenantRequest
	3,  // 7: identity.tenant.v1.TenantService.GetTenantBySlug:input_type -> identity.tenant.v1.GetBySlugRequest
	4,  // 8: identity.tenant.v1.TenantService.ValidateTenant:input_type -> identity.tenant.v1.ValidateTenantRequest
	7,  // 9: identity.tenant.v1.TenantService.ListTenants:input_type -> identity.tenant.v1.ListTenantsRequest
	6,  // 10: identity.tenant.v1.TenantService.GetTenant:output_type -> identity.tenant.v1.TenantResponse
	6,  // 11: identity.tenant.v1.TenantService.GetTenantBySlug:output_type -> identity.tenant.v1.TenantResponse
	5,  // 12: identity.tenant.v1.TenantService.ValidateTenant:output_type -> identity.tenant.v1.ValidationResponse
	8,  // 13: identity.tenant.v1.TenantService.ListTenants:output_type -> identity.tenant.v1.ListTenantsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_tenant_v1_tenant_proto_init() }
func file_proto_tenant_v1_tenant_proto_init() {
	if File_proto_tenant_v1_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tenant_v1_tenant_proto_rawDesc), len(file_proto_tenant_v1_tenant_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tenant_v1_tenant_proto_goTypes,
		DependencyIndexes: file_proto_tenant_v1_tenant_proto_depIdxs,
		EnumInfos:         file_proto_tenant_v1_tenant_proto_enumTypes,
		MessageInfos:      file_proto_tenant_v1_tenant_proto_msgTypes,
	}.Build()
	File_proto_tenant_v1_tenant_proto = out.File
	file_proto_tenant_v1_tenant_proto_goTypes = nil
	file_proto_tenant_v1_tenant_proto_depIdxs = nil
}
